src/Entity/UserToken.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserTokenRepository")
 */
class UserToken
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $registration;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $forgotPassword;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="userToken", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegistration(): ?string
    {
        return $this->registration;
    }

    public function setRegistration(string $registration): self
    {
        $this->registration = $registration;

        return $this;
    }

    public function getForgotPassword(): ?string
    {
        return $this->forgotPassword;
    }

    public function setForgotPassword(?string $forgotPassword): self
    {
        $this->forgotPassword = $forgotPassword;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/tpl-part/courcailler.html.twig
{% for courcaillet in pagination %}

    <div class="courcaillet">
        <div class="flex">
            <img class="profilPic" width="40" height="40" src="{{ vich_uploader_asset( courcaillet.userNbr, 'avatarFile' ) | imagine_filter('avatar') }}">
            <h4><a href="{{ path('profile', { id: courcaillet.userNbr.id }) }}">@{{ courcaillet.userNbr.pseudo }}</a></h4>
            {% if app.user.id == courcaillet.userNbr.id %}
                <button class="btn-suppr" type="submit"><a href="{{ path('deleteCourcaillet', { courcailletId: courcaillet.id} ) }}">Supprimer</a></button>
            {% endif %}
        </div>
        <p class="">Le {{ courcaillet.date|date("d/m/Y") }} à {{ courcaillet.date|date("H:i:s") }}s</p>
        <hr>
        <div class="">
            <p class="text-center">{{ courcaillet.content }}</p>
        </div>
        <hr>
        <div>
{#            Mentions#}
            {% if courcaillet.mention|length > 0 %}
                <p class="text-center">Mentions :
                    {% for person in courcaillet.mention %}
                        <a href="{{ path('profile', { id: person.id }) }}">@{{ person.pseudo }} {% if not loop.last %}|{% endif %}</a>
                    {% endfor %}
                </p>
            {% endif %}

{#            Hashtags#}
            {% if courcaillet.hashtags|length > 0 %}
                <p class="text-center">Hashtags :
                    {% for hashTag in courcaillet.hashtags %}
                        <a href="{{ path('hashtag', { tag: hashTag.name }) }}">#{{ hashTag.name }} {% if not loop.last %}|{% endif %}</a>
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    </div>
{% endfor %}

templates/tpl-part/courcaillerNoUserName.html.twig
{% for courcaillet in pagination %}

    <div class="courcaillet">
        <div class="flex">
            <p class="">Le {{ courcaillet.date|date("d/m/Y") }} à {{ courcaillet.date|date("H:i:s") }}s</p>
            {% if app.user.id == courcaillet.userNbr.id %}
                <button class="btn-suppr" type="submit"><a href="{{ path('deleteCourcaillet', { courcailletId: courcaillet.id} ) }}">Supprimer</a></button>
            {% endif %}
        </div>

        <hr>
        <div class="">
            <p class="text-center">{{ courcaillet.content }}</p>
        </div>
        <hr>
        <div class="">
            {#            Mentions#}
            {% if courcaillet.mention|length > 0 %}
                <p class="text-center">Mentions :
                    {% for person in courcaillet.mention %}
                        <a href="{{ path('profile', { id: person.id }) }}">@{{ person.pseudo }} {% if not loop.last %}|{% endif %}</a>
                    {% endfor %}
                </p>
            {% endif %}

            {#            Hashtags#}
            {% if courcaillet.hashtags|length > 0 %}
                <p class="text-center">Hashtags :
                    {% for hashTag in courcaillet.hashtags %}
                        <a href="{{ path('hashtag', { tag: hashTag.name }) }}">#{{ hashTag.name }} {% if not loop.last %}|{% endif %}</a>
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    </div>
{% endfor %}

templates/tpl-part/footer.html.twig
{% block footer %}
<footer>
    <div class="ctnr">
        <div class="flex-column">
            <h4 class="text-center">Courcaillez !</h4>
            <a class="button" href="{{ path('rgpd') }}">Mentions légales</a>

        </div>
    </div>
</footer>
{% endblock %}

templates/tpl-part/header.html.twig
{% block header %}
    <header>
        <div class="ctnr">
            <div class="flex">
                <h5>Courcaillez !</h5>
                <img class="profilPic" src="{{ vich_uploader_asset( app.user, 'avatarFile' ) | imagine_filter('avatar')}}">
                <div>
                    <h5 class="uk-text-left">@{{ app.user.pseudo }},<br>
                        vous êtes connecté</h5>
                </div>
                <button class="button waves-effect waves-teal"><a href="{{ path('start') }}">Accueil</a></button>
                <button class="button waves-effect waves-teal"><a href="/profile/{{ app.user.id }}">Mon profil</a></button>
                <button class="button waves-effect waves-red"><a href="{{ path('app_logout') }}">Déconnexion</a></button>
                <div>
                    <a id="searchBtn" class="btn-floating btn-large waves-effect waves-yellow teal"><i class="material-icons">search</i></a>
                </div>
            </div>
        </div>
        <div id="searchPopUp" class="hide">
            <div id="searchBoxCloseBtn">
                <a class="waves-effect waves-light btn"><i class="material-icons">close</i></a>
            </div>
            <nav>
                <div class="nav-wrapper">
                    <form>
                        <div class="input-field">
                            <input id="search" type="search" required autocomplete="off">
                            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                            <i class="material-icons">close</i>
                        </div>
                    </form>
                </div>
            </nav>
            <ul id="searchResults" class="collapsible">
                <li class="active">
                    <div class="collapsible-header"><i class="material-icons">person</i>@Cailles</div>
{#                    Here goes the axios response in user database like chips#}
                    <div id="usersResultBox" class="collapsible-body">
                    </div>
                </li>
                <li>
                    <div class="collapsible-header"><i class="material-icons">gesture</i>#Hashtags</div>
{#                    Here goes the axios response in hashtags database like chips#}
                    <div id="hashtagResultBox" class="collapsible-body">
                    </div>
                </li>
{#                <li>#}
{#                    <div class="collapsible-header"><i class="material-icons">message</i>Courcaillets</div>#}
{#                    <div class="collapsible-body">#}
{#                        <div class="chip">#}
{#                            <img src="/{{ asset('uploads/pictos/trash-can.png') }}" alt="Contact Person">#}
{#                            <a href="{{ path('hashtag', {'tag': 'hello'}) }}">#}
{#                                Contenu du courcaillet héhé#}
{#                            </a>#}
{#                        </div>#}
{#                    </div>#}
{#                </li>#}
            </ul>
        </div>
    </header>
{% endblock %}